### ISSUE TITLE
using `match.fun()` to find functions with the same name as the sheet being read

### ISSUE THREAD

**Issue by aammd** [SrivastavaLab/bwg#1]
Is it dangerous or risky to use `match.fun()` to find a package's own functions? small example of code in question [here](https://github.com/SrivastavaLab/bwg/blob/340eb74d9ef9be1d1537bb124bb74ee460413681/R/demo.R) 

*background* The package has a specialized purpose: reading data in from excel files which are stored in dropbox. the backstory is that we have results from many international replicates of an experiment. the package uses Karthik Ram's `rdrop2` and Hadley Wickham's `readxl` packages. This way scientists on the project can get their data directly into R from the excel files in their dropbox, without ever actually opening Dropbox.

All the excel files are made from the same template, so they _should_ be in a standardized form. Therefore a function that works for one will work for all.

Within each excel file there are multiple tabs. each tab is different, and needs to be read in with specific arguments.

**the problem**: how can I allow users to simply say which tab (aka "sheet") they want, without having to set default arguments manually every time?

**Andrew's solution**: create a function with the exact same name as the tab in question (here `leaf.waterdepths()`). the function reads in the tab **of the same name** with all the correct arguments. When users ask for a sheet, my function `read_sheet()` uses `match.fun()` to find the correct reading function.

**Comment by sckott** [comment]
hmm, maybe like 

```r
sheet = "apple"
sheet = match.fun(sheet, c("apple", "orange"))
fun = switch(sheet, 
                    apple = leaf.waterdepths, 
                    orange = stuff.things)
fun(...)
```

**Comment by aammd** [comment]
Not sure I understand that, @sckott . Even just this bit
```r
sheet = "apple"
sheet = match.fun(sheet, c("apple", "orange"))
```
immediately throws an error. What am i missing?

**Comment by sckott** [comment]
sorry, fixed!

**Comment by naupaka** [comment]
Is there a sample of one of these xls sheets I could see to get a sense for how they look?

**Comment by naupaka** [comment]
I like Scott's idea though. The [help page for `match.arg()`](https://stat.ethz.ch/R-manual/R-devel/library/base/html/match.arg.html) makes it seem like a good choice to use here, if I am understanding the problem correctly.

**Comment by aammd** [comment]
example data is now it the `/data-raw` directory

**Comment by aammd** [comment]
omg guys. `switch()`.

**Comment by sckott** [comment]
:heart:   `switch()`

**Comment by naupaka** [comment]
Are the sheets in the file always the same? There's also `read_sheets()` in `readxl` to get you a list of them.

**Comment by aammd** [comment]
seriously tho. What an amazing way to create a lookup table

**Comment by sckott** [comment]
i know, it's a great thing

**Comment by aammd** [comment]
Thank you Scott! I have refined it with your suggestion and it works much better. This also saves me from need to export the reading function.

**Comment by sckott** [comment]
:rocket: :rocket:
